const neutral = {
  ink: '#17212B',
  body: '#47515D',
  muted: '#6F7782',
  faint: '#9AA2AC',
  line: '#DDE4E8',
  softLine: '#E9EEF1',
  canvas: '#F4F6F5',
  wash: '#EEF2F0',
  paper: '#FFFFFF',
};

export const Colors = {
  background: neutral.canvas,
  surface: neutral.paper,
  card: neutral.paper,
  cardLight: neutral.wash,
  glass: neutral.paper,
  glassBorder: neutral.softLine,
  primary: '#178864',
  secondary: '#1F9E9A',
  tertiary: '#D84D5A',
  warning: '#C47A23',
  text: neutral.ink,
  textMuted: neutral.muted,
  textSoft: neutral.faint,
  border: neutral.line,
  borderSoft: neutral.softLine,
  transparent: 'transparent',
  primaryGlow: '#E5F3EE',
  secondaryGlow: '#E1F2F1',
  tertiaryGlow: '#F9E5E7',
  warningGlow: '#F7EBDD',
  shadow: 'rgba(24, 32, 42, 0.08)',
};

export const Layout = {
  compactPhone: 380,
  phone: 430,
  tablet: 900,
  desktop: 900,
  desktopExpanded: 1200,
  contentMax: 1520,
  pageMax: 1040,
  cardRadius: 14,
  panelRadius: 16,
  controlRadius: 10,
};
