import { StyleSheet } from 'react-native';

import { Colors } from '@/constants/Colors';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: Colors.card,
    borderRadius: 14,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  iconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: Colors.primaryGlow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: {
    flex: 1,
  },
  title: {
    fontSize: 17,
    fontWeight: '800',
    color: Colors.text,
  },
  subtitle: {
    fontSize: 13,
    color: Colors.textMuted,
    fontWeight: '500',
    marginTop: 3,
    lineHeight: 18,
  },
  messages: {
    gap: 8,
    marginBottom: 14,
  },
  messageBubble: {
    maxWidth: '88%',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  assistantBubble: {
    alignSelf: 'flex-start',
    backgroundColor: Colors.cardLight,
  },
  userBubble: {
    alignSelf: 'flex-end',
    backgroundColor: Colors.primary,
  },
  loadingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  messageText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  assistantText: {
    color: Colors.text,
  },
  userText: {
    color: '#FFFFFF',
  },
  estimateBox: {
    borderRadius: 12,
    backgroundColor: Colors.primaryGlow,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#CFE9DF',
    gap: 10,
  },
  estimateHeader: {
    gap: 2,
  },
  estimateValue: {
    color: Colors.primary,
    fontSize: 25,
    fontWeight: '900',
  },
  estimateMeta: {
    color: Colors.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  activityRow: {
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#CFE9DF',
  },
  activityName: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  activityMeta: {
    color: Colors.textMuted,
    fontSize: 13,
    fontWeight: '600',
    marginTop: 3,
  },
  applyButton: {
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: Colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 14,
    marginTop: 2,
  },
  applyButtonDisabled: {
    opacity: 0.72,
  },
  applyButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  entriesBox: {
    borderRadius: 12,
    backgroundColor: Colors.cardLight,
    padding: 12,
    marginBottom: 14,
    gap: 8,
  },
  entriesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  entriesTitle: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  entriesEmpty: {
    color: Colors.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  entryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.borderSoft,
  },
  entryInfo: {
    flex: 1,
    minWidth: 0,
  },
  entryName: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  entryMeta: {
    color: Colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  deleteButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    flexShrink: 0,
  },
  errorText: {
    color: Colors.tertiary,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 12,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 10,
  },
  input: {
    flex: 1,
    minHeight: 48,
    maxHeight: 110,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: Colors.text,
    fontSize: 14,
    fontWeight: '600',
    textAlignVertical: 'top',
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonDisabled: {
    opacity: 0.48,
  },
});
